<b>STORAGE:</b><br/>
1. The Storer:<br/>
(a) may store Goods in the Space allocated to the Storer by the Facility Owner ("FO"), and only in that Space:<br/>
(b) has knowledge of the Goods in the Space;<br/>
(c) warrants that they are the owner of the Goods in the Space, and/or are entitled at law to deal with them in accordance with all aspects of this Agreement.<br/>
2. The FO:<br/>
(a) does not have and will not be deemed to have, knowledge of the Goods;<br/>
(b) is not a bailee nor a warehouseman of the Goods and the Storer acknowledges that the FO does not take possession of the Goods;<br/>
(c) claims a contractual lien over the Goods in the event any moneys are owing under the Agreement.<br/>
<b>COST:</b><br/>
3. The Storer must upon signing the Agreement pay to the FO:<br/>
(a) the Deposit (which, when applicable, will be refunded within 30 days of termination of this Agreement) and/or<br/>
(b) the Administration Fee.<br/>
4. The Storer is responsible to pay:<br/>
(a) the Storage Fee being the amount indicated in this Agreement or the amount notified to the Storer by the FO from time to time. The Storage Fee is payable in advance and it is the Storer's responsibility to make payment directly to the FO on time, and in full, throughout the period of storage. Any Storage Fees paid by direct deposit/direct credit ("Direct Payment") will not be credited to Storer's account unless the Storer identifies the
Direct Payment clearly and as reasonably directed by the FO. The FO is indemnified from any claim for enforcement of the Agreement, including the sale or disposal of Goods, due to the Storer’s failure to correctly identify a Direct Payment;<br/>
(b) the Cleaning Fee, as indicated on the front on this Agreement, is payable at the FO's reasonable discretion;<br/>
(c) a Late Payment Fee, as indicated on the front on this Agreement, which becomes payable each time a payment is late;<br/>
(d) any reasonable costs incurred by the FO in collecting late or unpaid Storage Fees, or in enforcing this Agreement in any way, including but not limited to postal, telephone, debt collection, personnel and/ or the Default Action costs.<br/>
5. The Storer will be responsible for payment of any government taxes or charges (including any goods and services tax) being levied on this Agreement, or any supplies pursuant to this Agreement.<br/>
<b>DEFAULT:</b><br/>
6. (a) Notwithstanding clause 23,and subject to clause 6 (b), the Storer acknowledges that, in the event of the Storage Fee, or any other moneys owing under this Agreement, not being paid in full within 42 days of the due date, the FO may enter the Space, by force or otherwise, retain the Deposit and/or sell or dispose of any Goods in the Space on such terms that the FO may determine ("Default Action"). For the purposes of the Personal Property Securities Act 2009, the FO is deemed to be in possession of the Goods from the moment the FO accesses the Space. The Storer consents to and authorises the sale or disposal of all Goods regardless of their nature or value. The FO may also require payment of Default Action costs, including any costs associated with accessing the Storer's Space and disposal or sale of the Storer's Goods. Any excess funds will be returned to the Storer within 6 months of the sale of goods. In the event that the Storer cannot be located, excess funds will be deposited with the Public Trustee or equivalent authority. In the event that the Storer has more than one Space with the FO, default on either Space authorises the FO to take Default Action against all Spaces.<br/>
(b) At least 14 days before the FO can take any Default Action the FO will provide the Storer with Notice that the Storer is in Default. The FO will provide the Storer with reasonable time to rectify the Default before any Default Action is taken.<br/>
(c) If the FO reasonably believes it is a health and safety risk to conduct an inventory of Goods in the Space, subject to the FO providing the Storer with reasonable prior notice to pay outstanding moneys and collect the goods, the FO may dispose of some or all of the Goods without undertaking an inventory. Further, due to the inherent health and safety risks in relation to undertaking any sale or disposal of Goods whereby the FO must handle the Storer's Goods, the FO need not open or empty bags or boxes to undertake an inventory or assess the contents therein, and may elect to instead dispose of all bagged and/or boxed items without opening them.<br/>
<b>RIGHT TO DUMP:</b><br/>
7. If, in the reasonable opinion of the FO, a defaulting Storer's Goods are either not saleable, fail to sell when offered for sale, may pose a health risk to staff or the public if handled, or are not of sufficient value to warrant the expense of attempting to sell, the FO may dispose of all Goods in the Storer's Space by any means.<br/>
8. Further, upon Termination of the Agreement (Clause 23) by either the Storer or the FO, in the event that a Storer fails to remove all Goods from their Space or the Facility the FO is authorised to dispose of all Goods by any means 7 days from the Termination Date, regardless of the nature or value of the Goods. The FO will give 7 days' notice of intended disposal.<br/>
9. Any items deemed left, in the FO's reasonable opinion, unattended in common areas or outside the Storer's Space at any time may at the FO's reasonable discretion be sold, disposed, moved or dumped immediately and at the expense and liability of the Storer.<br/>
<b>ACCESS AND CONDITIONS:</b><br/>
10. The Storer:<br/>
(a) has the right to access the Space during Access Hours as posted by the FO and subject to the terms of this Agreement;<br/>
(b) will be solely responsible for the securing of the Space and shall so secure the Space at all times when the Storer is not in the Space in a manner reasonably acceptable to the FO, and where applicable will secure the external gates and/or doors of the Facility. The Storer is not permitted to apply a padlock to their Space in the FO’s overlocking position, and the Storer may have any such padlock forcefully cut off at the Storer's expense;<br/>
(c) must not store any Goods that are hazardous, illegal, stolen, inflammable, explosive, environmentally harmful, perishable, living, or that are a risk to the property of any person;<br/>
(d) must not store items which are irreplaceable, such as currency, jewellery, furs, deeds, paintings, curios, works of art, items of personal sentimental value and/or any items that are worth more than $2000AUD in total unless they are itemised and covered by insurance;<br/>
(e) will use the Space solely for the purpose of storage and shall not carry on any business or other activity in the Space;<br/>
(f) must not attach nails, screws etc to any part of the Space, must maintain the Space by ensuring it is clean and in a state of good repair, and must not damage or alter the Space without the FO’s consent; in the event of uncleanliness of or damage to the Space or Facility the FO will be entitled to retain the Storer's Deposit, charge a Cleaning Fee, and/or full reimbursement by the Storer to the value of the repairs and/or cleaning;<br/>
(g) cannot assign this Agreement;<br/>
(h) must give Notice of the change of address, phone numbers or email address of the Storer or the Alternate Contact Person ("ACP") within 48 hours of any change;<br/>
(i) grants the FO entitlement to discuss any default by and any information it holds regarding the Storer with the ACP registered on the front of this Agreement. Further, where the FO reasonably believes that the Storer is unwilling or unable to remove Goods from the Space upon termination or default of the Agreement, despite reasonable notice under these terms, the Facility Owner may allow the ACP to remove the Goods on such terms as agreed between the FO and the ACP without the need for further consent from the Storer.<br/>
(j) is solely responsible for determining whether the Space is appropriate and suitable for storing the Storer’s Goods, having specific consideration for the size, nature and condition of the Space and Goods.<br/>
(k) must ensure their Goods are free of food scraps and are not damp when placed into storage.<br/>
11. In addition to clause 6, the FO has the right to refuse access to the Space and/or the Facility where any moneys are owing by the Storer to the FO where a demand or notice relating to payment of such monies has been made.<br/>
12. The FO will not be liable for any loss or damaged suffered by the Storer resulting from any inability to access the Facility or the Space.<br/>
13. The FO reserves the right to relocate the Storer to another Space under certain circumstances, including but not limited to unforeseen extraordinary events or redevelopment of the Facility.<br/>
14. The FO may dispose of the Storer’s Goods in the event that Goods are damaged due to fire, flood or other event that has rendered Goods, in the reasonable opinion of the FO severely damaged, or dangerous to the Facility, any persons, or other Storers and/or their Goods. Where practicable, the FO will provide the Storer with reasonable Notice and an opportunity to review the Goods before the Goods are disposed of.<br/>
15. The Storer acknowledges that it has raised with the FO all queries relevant to its decision to enter this Agreement and that the FO has, prior to the Storer entering into this Agreement, answered all such queries to the satisfaction of the Storer. The Storer acknowledges that any matters resulting from such queries have, to the extent required by the Storer and agreed to by the FO, been reduced to writing and incorporated into the terms of this Agreement.<br/>
15A The Storer is responsible (and must pay) for loss or damage caused by a third party who enters the Space or the Facility at the request, direction, or as facilitated by the Storer (including provision of gate key code or swipe card).<br/>
<b>RISK AND RESPONSIBILITY:</b><br/>
16. The FO's services come with non-excludable guarantees under consumer protection law, including that they will be provided with due care and skill. Otherwise, to the extent permitted by law, the Goods are stored at the sole risk and responsibility of the Storer who shall be responsible for any and all theft, damage to, and deterioration of the Goods, and shall bear the risk of any and all damage caused by flood or fire or leakage or overflow of
water, mildew, mould, heat, spillage of material from any other space, removal or delivery of the Goods, pest or vermin or any other reason whatsoever.<br/>
17. Where loss, damage or injury is caused by the Storer, the Storer’s actions or the Storer’s Goods, the Storer agrees to indemnify and keep indemnified the FO from all claims for any loss of or damage to the property of, or personal injury to or death of the Storer, the Facility, the FO or third parties resulting from or incidental to the use of the Space by the Storer, including but not limited to the storage of Goods in the Space, the Goods themselves and/or accessing the Facility.<br/>
18. Certain laws may apply to the storage of goods including criminal, bankruptcy, liquidation and others. The Storer acknowledges and agrees to comply with all relevant laws, including Acts and Ordinances, Regulations, By-laws, and Orders, as are or may be applicable to the use of the Space. This includes laws relating to the material which is stored, and the manner in which it is stored. Such liability and responsibility rests with the Storer, and includes any and all costs resulting from such a breach.<br/>
19. If the FO reasonably believes that the Storer is not complying with any relevant laws the FO may take any action as it reasonably believes to be necessary, including the action outlined in clauses 21 & 23, contacting, cooperating with and/or submitting Goods to the relevant authorities, and/or immediately disposing of or removing the Goods at the Storer’s expense, including where in the FO’s reasonable opinion the Storer is engaging in illegal activity in relation to the storage of the Goods. No failure or delay by the FO to exercise its rights under this Agreement will operate to waive those rights.<br/>
<b>INSPECTION AND ENTRY BY THE FO:</b><br/>
20. Subject to clause 21 the Storer consents to inspection and entry of the Space by the FO provided that the FO gives 14 days Notice.<br/>
21. In the event of an emergency, that is where obliged to do so by law or in the event that property, the environment or human life is, in the reasonable opinion of the FO, threatened, the FO may enter the Space using all necessary force without the consent of the Storer, but the FO shall thereafter notify the Storer as soon as practicable. The Storer consents to such entry.<br/>
21A The Storer agrees that in circumstances where the FO reasonably suspects a breach of the law or damage to the facility, the FO may use a microprobe or other CCTV camera to view the inside of the Space and any footage obtained which evidences a breach of the Agreement or the law may be relied upon by the FO to take any action authorised under this Agreement, including terminating the Agreement and/or cooperating with law enforcement agencies and other authorities.<br/>
22. NOTICE: Notice will usually be given by email or SMS, or otherwise will be left at, or posted to, or faxed to the address of the Storer. In relation to the giving of Notice by the Storer to the FO, Notice must be in writing and actually be received to be valid, and the FO may specify a required method. In the event of not being able to contact the Storer, Notice is deemed to have been given to the Storer by the FO if the FO has sent Notice to the last notified address or has sent Notice via any other contact method, including by SMS or email to the Storer or the ACP without any electronic ‘bounce back’ or similar notification. In the event that there is more than one Storer, Notice to or by any single Storer is agreed to be sufficient for the purposes of any Notice requirement under this Agreement<br/>
23. TERMINATION: Once the initial fixed period of storage has ended, either party may terminate this Agreement by giving the other party Notice of the Termination Date in accordance with period indicated on the front of this Agreement. In the event of any activities reasonably considered by the FO to be illegal or environmentally harmful on the part of the Storer the FO may terminate the Agreement without Notice. The FO is entitled to retain or charge apportioned storage fees if less than the requisite Notice is given by the Storer. The Storer must remove all Goods in the Space before the close of business on the Termination Date and leave the Space in a clean condition and in a good state of repair to the satisfaction of the FO. In the event that Goods are left in the Space after the Termination Date, clause 8 will apply. The Storer must pay any outstanding Storage Fees and any expenses on default or any other moneys owed to the FO up to the Termination Date, or clauses 6, 7 or 8 may apply. Any calculation of the outstanding fees will be by the FO. If the FO enters the Space for any reason and there are no Goods stored therein, the FO may terminate the Agreement without giving prior Notice, but the FO will send Notice to the Storer within 7 days.<br/>
24. The Parties' liability for outstanding moneys, property damage, personal injury, environmental damage and legal responsibility under this Agreement continues to run beyond the termination of this Agreement.<br/>
25. SEVERANCE If any clause, term or provision of this Agreement is legally unenforceable or is made inapplicable, or in its application would breach any law, that clause, term or provision shall be severed or read down, but so as to maintain (as far as possible) all other terms of the Agreement.<div id="terms-bottom"></div>